version: "3.4"

services:
  lanka:
    image: btl/lanka:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
      - "80:8080"
      - "443:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0.36-debian
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - db

volumes:
  db_data:
